server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;
    location = /docs/cm {
        return 404;
    }
    location = /docs/cm.md {
        return 404;
    }
    location ^~ /docs/cm/ {
        return 404;
    }
    location ~ \.md$ {
        types {}
        default_type "text/markdown; charset=utf-8";
        try_files $uri =404;
    }
    location / {
        try_files $uri.html $uri $uri/ /index.html;
    }
    location ~* \.(?:ico|css|js|gif|jpe?g|png|woff2?|eot|ttf|otf|svg|map)$ {
        expires 6M;
        access_log off;
        add_header Cache-Control "public";
    }
    error_page 404 /404.html;
}
