/**
 * Copyright 2026 GoodRx, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import fs from "node:fs";
import path from "node:path";
import fg from "fast-glob";
import matter from "gray-matter";
import remarkGfm from "remark-gfm";
import remarkMdx from "remark-mdx";
import remarkParse from "remark-parse";
import remarkStringify from "remark-stringify";
import { unified } from "unified";

export const GENERATED_RAW_MARKDOWN_SENTINEL =
  "<!-- GENERATED BY scripts/generateRawMarkdown.ts. DO NOT EDIT. -->";

export type RawMarkdownRoute = {
  outputRelativePath: string;
  route: string;
  sourceRelativePath: string;
};

export type RawMarkdownPage = RawMarkdownRoute & {
  markdown: string;
  sourcePath: string;
};

export type RawMarkdownGenerationOptions = {
  check?: boolean;
  rootDir?: string;
};

export type RawMarkdownGenerationResult = {
  outdatedCount: number;
  projectedCount: number;
  removedCount: number;
  staleCount: number;
  writtenCount: number;
};

type Position = {
  start?: {
    column?: number;
    line?: number;
  };
};

type AstNode = {
  [key: string]: unknown;
  attributes?: AstNode[];
  children?: AstNode[];
  data?: {
    estree?: AstNode;
  };
  meta?: string | null;
  name?: string | null;
  position?: Position;
  type: string;
  value?: unknown;
};

type TransformContext = {
  lineOffset: number;
  sourcePath: string;
};

const STANDARD_PHRASE_NODES = new Set([
  "break",
  "delete",
  "emphasis",
  "footnoteReference",
  "image",
  "imageReference",
  "inlineCode",
  "link",
  "linkReference",
  "strong",
  "text",
]);

const DECORATIVE_CALLOUT_EMOJI_LITERALS = new Set(["⚠️"]);
const DECORATIVE_CALLOUT_ICON_NAMES = new Set(["Info"]);

function normalizedSourceRelativePath(sourceRelativePath: string): string {
  const normalized = sourceRelativePath.replace(/\\/g, "/");
  const segments = normalized.split("/");
  if (
    !normalized ||
    path.posix.isAbsolute(normalized) ||
    !normalized.endsWith(".mdx") ||
    segments.some((segment) => !segment || segment === "." || segment === "..")
  ) {
    throw new Error(
      `Documentation source path must be a safe relative .mdx path: ${sourceRelativePath}`,
    );
  }
  return normalized;
}

export function sourceRelativePathToDocsRoute(
  sourceRelativePath: string,
): string {
  const normalized = normalizedSourceRelativePath(sourceRelativePath);
  let slug = normalized.slice(0, -".mdx".length);
  if (slug === "index") slug = "";
  else if (slug.endsWith("/index")) slug = slug.slice(0, -"/index".length);
  return slug ? `/docs/${slug}` : "/docs";
}

export function docsRouteToRawOutputRelativePath(route: string): string {
  if (
    route !== "/docs" &&
    (!route.startsWith("/docs/") ||
      route.endsWith("/") ||
      route.split("/").some((segment) => segment === "." || segment === ".."))
  ) {
    throw new Error(`Invalid documentation route: ${route}`);
  }
  return route === "/docs" ? "docs.md" : `${route.slice(1)}.md`;
}

export function docsRouteToHtmlOutputRelativePath(route: string): string {
  docsRouteToRawOutputRelativePath(route);
  return route === "/docs" ? "docs.html" : `${route.slice(1)}.html`;
}

export function sourceRelativePathToRawOutputRelativePath(
  sourceRelativePath: string,
): string {
  return docsRouteToRawOutputRelativePath(
    sourceRelativePathToDocsRoute(sourceRelativePath),
  );
}

export function rawMarkdownRouteForSource(
  sourceRelativePath: string,
): RawMarkdownRoute {
  const normalized = normalizedSourceRelativePath(sourceRelativePath);
  const route = sourceRelativePathToDocsRoute(normalized);
  return {
    outputRelativePath: docsRouteToRawOutputRelativePath(route),
    route,
    sourceRelativePath: normalized,
  };
}

export function validateRawRouteCollisions(routes: RawMarkdownRoute[]): void {
  const byRoute = new Map<string, string>();
  const byOutput = new Map<string, string>();
  for (const item of routes) {
    const priorRoute = byRoute.get(item.route);
    if (priorRoute) {
      throw new Error(
        `Raw Markdown route collision: ${priorRoute} and ${item.sourceRelativePath} both map to ${item.route}`,
      );
    }
    byRoute.set(item.route, item.sourceRelativePath);

    const priorOutput = byOutput.get(item.outputRelativePath);
    if (priorOutput) {
      throw new Error(
        `Raw Markdown output collision: ${priorOutput} and ${item.sourceRelativePath} both map to ${item.outputRelativePath}`,
      );
    }
    byOutput.set(item.outputRelativePath, item.sourceRelativePath);
  }
}

export function validateExportedFileBijection(
  routes: RawMarkdownRoute[],
): void {
  const htmlFiles = new Map<string, string>();
  const rawFiles = new Map<string, string>();

  for (const item of routes) {
    const expectedRaw = docsRouteToRawOutputRelativePath(item.route);
    const html = docsRouteToHtmlOutputRelativePath(item.route);
    if (item.outputRelativePath !== expectedRaw) {
      throw new Error(
        `Exported documentation file mismatch: ${item.sourceRelativePath} maps to ${html}, so its raw counterpart must be ${expectedRaw}, not ${item.outputRelativePath}`,
      );
    }

    const priorHtml = htmlFiles.get(html);
    if (priorHtml) {
      throw new Error(
        `Exported HTML file collision: ${priorHtml} and ${item.sourceRelativePath} both map to ${html}`,
      );
    }
    htmlFiles.set(html, item.sourceRelativePath);

    const priorRaw = rawFiles.get(expectedRaw);
    if (priorRaw) {
      throw new Error(
        `Exported raw Markdown file collision: ${priorRaw} and ${item.sourceRelativePath} both map to ${expectedRaw}`,
      );
    }
    rawFiles.set(expectedRaw, item.sourceRelativePath);
  }

  if (htmlFiles.size !== rawFiles.size || htmlFiles.size !== routes.length) {
    throw new Error(
      `Exported documentation file mismatch: found ${htmlFiles.size} HTML file(s), ${rawFiles.size} raw Markdown file(s), and ${routes.length} route(s)`,
    );
  }
}

export function validateDocumentationSourcePaths(
  sourceRelativePaths: string[],
): number {
  const normalized = sourceRelativePaths.map(normalizedSourceRelativePath);
  const retired = normalized.filter(
    (item) => item === "cm.mdx" || item.startsWith("cm/"),
  );
  if (retired.length > 0) {
    throw new Error(
      `The retired /docs/cm route namespace cannot contain source pages: ${retired.sort().join(", ")}`,
    );
  }
  return normalized.length;
}

function location(node: AstNode, context: TransformContext): string {
  const line = node.position?.start?.line;
  const column = node.position?.start?.column;
  if (line === undefined) return context.sourcePath;
  return `${context.sourcePath}:${line + context.lineOffset}:${column ?? 1}`;
}

function unsupported(
  node: AstNode,
  context: TransformContext,
  detail: string,
): never {
  const name = node.name ? ` <${node.name}>` : "";
  throw new Error(
    `${location(node, context)}: ${detail} [${node.type}${name}]`,
  );
}

function cloneScalarFields(
  node: AstNode,
  fields: string[],
): Record<string, unknown> {
  const cloned: Record<string, unknown> = { type: node.type };
  for (const field of fields) {
    if (node[field] !== undefined && node[field] !== null) {
      cloned[field] = node[field];
    }
  }
  return cloned;
}

function validateAttributes(
  node: AstNode,
  allowed: Set<string>,
  context: TransformContext,
): void {
  for (const attribute of node.attributes ?? []) {
    if (
      attribute.type !== "mdxJsxAttribute" ||
      typeof attribute.name !== "string"
    ) {
      unsupported(
        attribute,
        context,
        "JSX spread attributes are not supported",
      );
    }
    if (!allowed.has(attribute.name)) {
      unsupported(
        attribute,
        context,
        `Unsupported attribute "${attribute.name}" on <${node.name}>`,
      );
    }
  }
}

function findAttribute(node: AstNode, name: string): AstNode | null {
  return (
    node.attributes?.find(
      (attribute) =>
        attribute.type === "mdxJsxAttribute" && attribute.name === name,
    ) ?? null
  );
}

function requiredLiteralAttribute(
  node: AstNode,
  name: string,
  context: TransformContext,
): string {
  const attribute = findAttribute(node, name);
  if (!attribute || typeof attribute.value !== "string") {
    unsupported(
      attribute ?? node,
      context,
      `<${node.name}> requires a literal "${name}" attribute`,
    );
  }
  if (!attribute.value.trim()) {
    unsupported(
      attribute,
      context,
      `<${node.name}> requires a non-empty "${name}" attribute`,
    );
  }
  return attribute.value;
}

function optionalLiteralAttribute(
  node: AstNode,
  name: string,
  context: TransformContext,
): string | null {
  const attribute = findAttribute(node, name);
  if (!attribute) return null;
  if (typeof attribute.value !== "string") {
    unsupported(
      attribute,
      context,
      `<${node.name}> "${name}" must be a literal string`,
    );
  }
  return attribute.value;
}

function expressionFromEstree(node: AstNode): AstNode | null {
  const program = node.data?.estree;
  if (!program || program.type !== "Program" || !Array.isArray(program.body)) {
    return null;
  }
  if (program.body.length !== 1) return null;
  const statement = program.body[0];
  if (
    !statement ||
    statement.type !== "ExpressionStatement" ||
    typeof statement.expression !== "object" ||
    statement.expression === null
  ) {
    return null;
  }
  return statement.expression as AstNode;
}

function tabsLabels(node: AstNode, context: TransformContext): string[] {
  const attribute = findAttribute(node, "items");
  if (
    !attribute ||
    typeof attribute.value !== "object" ||
    attribute.value === null
  ) {
    unsupported(
      attribute ?? node,
      context,
      "<Tabs> requires an items string-array expression",
    );
  }
  const expression = expressionFromEstree(attribute.value as AstNode);
  if (
    !expression ||
    expression.type !== "ArrayExpression" ||
    !Array.isArray(expression.elements)
  ) {
    unsupported(
      attribute,
      context,
      "<Tabs> items must be a static array of string literals",
    );
  }
  const labels: string[] = [];
  for (const element of expression.elements) {
    if (
      typeof element !== "object" ||
      element === null ||
      (element as AstNode).type !== "Literal" ||
      typeof (element as AstNode).value !== "string"
    ) {
      unsupported(
        attribute,
        context,
        "<Tabs> items must contain only string literals",
      );
    }
    labels.push((element as AstNode).value as string);
  }
  return labels;
}

function literalStringExpression(
  node: AstNode,
  context: TransformContext,
): string {
  const expression = expressionFromEstree(node);
  if (
    !expression ||
    expression.type !== "Literal" ||
    typeof expression.value !== "string"
  ) {
    unsupported(
      node,
      context,
      "Only a static string expression is supported inside <code>",
    );
  }
  return expression.value;
}

function isReviewedCalloutIconElement(expression: AstNode): boolean {
  if (expression.type !== "JSXElement") return false;
  const opening = expression.openingElement;
  if (typeof opening !== "object" || opening === null) return false;
  const openingElement = opening as Record<string, unknown>;
  const name = openingElement.name;
  if (typeof name !== "object" || name === null) return false;
  const identifier = name as Record<string, unknown>;

  return (
    openingElement.type === "JSXOpeningElement" &&
    openingElement.selfClosing === true &&
    Array.isArray(openingElement.attributes) &&
    openingElement.attributes.length === 0 &&
    identifier.type === "JSXIdentifier" &&
    typeof identifier.name === "string" &&
    DECORATIVE_CALLOUT_ICON_NAMES.has(identifier.name) &&
    expression.closingElement === null &&
    Array.isArray(expression.children) &&
    expression.children.length === 0
  );
}

function validateCalloutDecoration(
  node: AstNode,
  context: TransformContext,
): void {
  const emoji = findAttribute(node, "emoji");
  if (emoji) {
    const expression =
      typeof emoji.value === "object" && emoji.value !== null
        ? expressionFromEstree(emoji.value as AstNode)
        : null;
    const reviewedEmoji =
      (typeof emoji.value === "string" &&
        DECORATIVE_CALLOUT_EMOJI_LITERALS.has(emoji.value)) ||
      (expression !== null && isReviewedCalloutIconElement(expression));
    if (!reviewedEmoji) {
      unsupported(
        emoji,
        context,
        '<Callout> "emoji" must be a reviewed static decoration: emoji="⚠️" or emoji={<Info />}',
      );
    }
  }

  const icon = findAttribute(node, "icon");
  if (icon) {
    const expression =
      typeof icon.value === "object" && icon.value !== null
        ? expressionFromEstree(icon.value as AstNode)
        : null;
    if (
      !expression ||
      expression.type !== "Identifier" ||
      typeof expression.name !== "string" ||
      !DECORATIVE_CALLOUT_ICON_NAMES.has(expression.name)
    ) {
      unsupported(
        icon,
        context,
        '<Callout> "icon" must be the reviewed static decoration icon={Info}',
      );
    }
  }
}

function transformPhrasingChildren(
  children: AstNode[] | undefined,
  context: TransformContext,
): AstNode[] {
  return (children ?? []).flatMap((child) =>
    transformPhrasingNode(child, context),
  );
}

function transformPhrasingNode(
  node: AstNode,
  context: TransformContext,
): AstNode[] {
  if (node.type === "mdxTextExpression") {
    unsupported(
      node,
      context,
      "Standalone MDX expressions are not supported; only static strings inside <code> can be projected",
    );
  }

  if (node.type === "mdxJsxTextElement") {
    if (node.name === "br") {
      validateAttributes(node, new Set(), context);
      if ((node.children?.length ?? 0) > 0) {
        unsupported(node, context, "<br> cannot have children");
      }
      return [{ type: "break" }];
    }

    if (node.name === "code") {
      validateAttributes(node, new Set(), context);
      let value = "";
      for (const child of node.children ?? []) {
        if (child.type === "text" && typeof child.value === "string") {
          value += child.value;
        } else if (child.type === "mdxTextExpression") {
          value += literalStringExpression(child, context);
        } else {
          unsupported(
            child,
            context,
            "<code> can contain only text or static string expressions",
          );
        }
      }
      return [{ type: "inlineCode", value }];
    }

    if (node.name === "div") {
      validateAttributes(node, new Set(["className"]), context);
      return transformPhrasingChildren(node.children, context);
    }

    unsupported(node, context, "Unsupported inline JSX element");
  }

  if (!STANDARD_PHRASE_NODES.has(node.type)) {
    unsupported(node, context, "Unsupported Markdown phrasing node");
  }

  switch (node.type) {
    case "text":
    case "inlineCode":
      if (typeof node.value !== "string") {
        unsupported(node, context, "Text node does not contain a string");
      }
      return [{ type: node.type, value: node.value }];
    case "break":
      return [{ type: "break" }];
    case "image":
      return [cloneScalarFields(node, ["url", "title", "alt"]) as AstNode];
    case "imageReference":
      return [
        cloneScalarFields(node, [
          "identifier",
          "label",
          "referenceType",
          "alt",
        ]) as AstNode,
      ];
    case "footnoteReference":
      return [cloneScalarFields(node, ["identifier", "label"]) as AstNode];
    case "link":
    case "linkReference": {
      const fields =
        node.type === "link"
          ? ["url", "title"]
          : ["identifier", "label", "referenceType"];
      return [
        {
          ...cloneScalarFields(node, fields),
          children: transformPhrasingChildren(node.children, context),
        } as AstNode,
      ];
    }
    case "delete":
    case "emphasis":
    case "strong":
      return [
        {
          type: node.type,
          children: transformPhrasingChildren(node.children, context),
        },
      ];
    default:
      return unsupported(node, context, "Unsupported Markdown phrasing node");
  }
}

function filenameParagraph(filename: string): AstNode {
  return {
    type: "paragraph",
    children: [
      {
        type: "strong",
        children: [{ type: "text", value: "File:" }],
      },
      { type: "text", value: " " },
      { type: "inlineCode", value: filename },
    ],
  };
}

function codeFilename(node: AstNode, context: TransformContext): string | null {
  const meta = node.meta?.trim();
  if (!meta) return null;

  const explicit = /(?:^|\s)filename=(?:"([^"]+)"|'([^']+)'|([^\s]+))/.exec(
    meta,
  );
  const filename = explicit
    ? (explicit[1] ?? explicit[2] ?? explicit[3])
    : null;
  let remaining = explicit
    ? `${meta.slice(0, explicit.index)} ${meta.slice(
        explicit.index + explicit[0].length,
      )}`
    : meta;
  remaining = remaining.replace(/\{[^{}]*\}/g, " ").trim();

  if (filename) {
    if (remaining) {
      unsupported(
        node,
        context,
        `Unsupported code-fence metadata after filename: ${remaining}`,
      );
    }
    return filename;
  }

  if (remaining && !/\s/.test(remaining) && !remaining.includes("=")) {
    return remaining;
  }
  if (!remaining) return null;
  unsupported(node, context, `Unsupported code-fence metadata: ${remaining}`);
}

function transformCode(node: AstNode, context: TransformContext): AstNode[] {
  if (typeof node.value !== "string") {
    unsupported(node, context, "Code block does not contain a string");
  }
  const code: AstNode = {
    type: "code",
    value: node.value,
  };
  if (typeof node.lang === "string" && node.lang) code.lang = node.lang;
  const filename = codeFilename(node, context);
  return filename ? [filenameParagraph(filename), code] : [code];
}

function transformCallout(node: AstNode, context: TransformContext): AstNode[] {
  validateAttributes(node, new Set(["emoji", "icon", "type"]), context);
  validateCalloutDecoration(node, context);
  const type = optionalLiteralAttribute(node, "type", context) ?? "info";
  const labels: Record<string, string> = {
    caution: "CAUTION",
    danger: "CAUTION",
    error: "CAUTION",
    important: "IMPORTANT",
    info: "NOTE",
    note: "NOTE",
    tip: "TIP",
    warning: "WARNING",
  };
  const label = labels[type.toLowerCase()];
  if (!label) {
    unsupported(node, context, `Unsupported Callout type "${type}"`);
  }
  const children = transformBlockChildren(node.children, context);
  const marker: AstNode = { type: "html", value: `[!${label}]\n` };
  if (children[0]?.type === "paragraph") {
    children[0] = {
      ...children[0],
      children: [marker, ...(children[0].children ?? [])],
    };
  } else {
    children.unshift({
      type: "paragraph",
      children: [{ type: "html", value: `[!${label}]` }],
    });
  }
  return [{ type: "blockquote", children }];
}

function transformTabs(node: AstNode, context: TransformContext): AstNode[] {
  validateAttributes(node, new Set(["items"]), context);
  const labels = tabsLabels(node, context);
  const tabs = node.children ?? [];
  if (tabs.length !== labels.length) {
    unsupported(
      node,
      context,
      `<Tabs> has ${labels.length} label(s) but ${tabs.length} tab panel(s)`,
    );
  }

  return tabs.flatMap((tab, index) => {
    if (
      !["mdxJsxFlowElement", "mdxJsxTextElement"].includes(tab.type) ||
      tab.name !== "Tabs.Tab"
    ) {
      unsupported(tab, context, "<Tabs> can contain only <Tabs.Tab> elements");
    }
    validateAttributes(tab, new Set(), context);
    return [
      {
        type: "paragraph",
        children: [
          {
            type: "strong",
            children: [{ type: "text", value: labels[index] }],
          },
        ],
      },
      ...transformBlockChildren(tab.children, context),
    ] as AstNode[];
  });
}

function transformCard(node: AstNode, context: TransformContext): AstNode {
  validateAttributes(node, new Set(["href", "title"]), context);
  const title = requiredLiteralAttribute(node, "title", context);
  const href = requiredLiteralAttribute(node, "href", context);
  const description = transformBlockChildren(node.children, context);
  const link: AstNode = {
    type: "link",
    url: href,
    children: [{ type: "text", value: title }],
  };

  if (description[0]?.type === "paragraph") {
    const [first, ...rest] = description;
    return {
      type: "listItem",
      children: [
        {
          type: "paragraph",
          children: [
            link,
            { type: "text", value: " — " },
            ...(first.children ?? []),
          ],
        },
        ...rest,
      ],
    };
  }

  return {
    type: "listItem",
    children: [{ type: "paragraph", children: [link] }, ...description],
  };
}

function transformCards(node: AstNode, context: TransformContext): AstNode[] {
  validateAttributes(node, new Set(), context);
  const items = (node.children ?? []).map((card) => {
    if (
      !["mdxJsxFlowElement", "mdxJsxTextElement"].includes(card.type) ||
      card.name !== "Cards.Card"
    ) {
      unsupported(
        card,
        context,
        "<Cards> can contain only <Cards.Card> elements",
      );
    }
    return transformCard(card, context);
  });
  return [{ type: "list", ordered: false, spread: false, children: items }];
}

function transformFlowJsx(node: AstNode, context: TransformContext): AstNode[] {
  switch (node.name) {
    case "Callout":
      return transformCallout(node, context);
    case "Steps":
      validateAttributes(node, new Set(), context);
      return transformBlockChildren(node.children, context);
    case "Tabs":
      return transformTabs(node, context);
    case "Cards":
      return transformCards(node, context);
    case "Image": {
      validateAttributes(
        node,
        new Set([
          "alt",
          "className",
          "height",
          "priority",
          "ratio",
          "src",
          "title",
          "width",
        ]),
        context,
      );
      const src = requiredLiteralAttribute(node, "src", context);
      const alt = requiredLiteralAttribute(node, "alt", context);
      const title = optionalLiteralAttribute(node, "title", context);
      return [
        {
          type: "paragraph",
          children: [
            {
              type: "image",
              url: src,
              alt,
              ...(title ? { title } : {}),
            },
          ],
        },
      ];
    }
    case "Iframe": {
      validateAttributes(node, new Set(["src", "title"]), context);
      const src = requiredLiteralAttribute(node, "src", context);
      const title = requiredLiteralAttribute(node, "title", context);
      return [
        {
          type: "paragraph",
          children: [
            {
              type: "link",
              url: src,
              children: [{ type: "text", value: title }],
            },
          ],
        },
      ];
    }
    case "div":
      validateAttributes(node, new Set(["className"]), context);
      return transformBlockChildren(node.children, context);
    case "br":
    case "code":
      return [
        {
          type: "paragraph",
          children: transformPhrasingNode(
            { ...node, type: "mdxJsxTextElement" },
            context,
          ),
        },
      ];
    case "Cards.Card":
      return unsupported(
        node,
        context,
        "<Cards.Card> must be a direct child of <Cards>",
      );
    case "Tabs.Tab":
      return unsupported(
        node,
        context,
        "<Tabs.Tab> must be a direct child of <Tabs>",
      );
    default:
      return unsupported(node, context, "Unsupported flow JSX element");
  }
}

function transformBlockChildren(
  children: AstNode[] | undefined,
  context: TransformContext,
): AstNode[] {
  return (children ?? []).flatMap((child) =>
    transformBlockNode(child, context),
  );
}

function transformBlockNode(
  node: AstNode,
  context: TransformContext,
): AstNode[] {
  switch (node.type) {
    case "mdxjsEsm": {
      const program = node.data?.estree;
      const body =
        program?.type === "Program" && Array.isArray(program.body)
          ? program.body
          : null;
      if (
        !body ||
        body.some(
          (statement) =>
            typeof statement !== "object" ||
            statement === null ||
            (statement as AstNode).type !== "ImportDeclaration",
        )
      ) {
        unsupported(
          node,
          context,
          "Only import declarations can be removed from raw Markdown",
        );
      }
      return [];
    }
    case "mdxFlowExpression":
    case "mdxTextExpression":
      return unsupported(
        node,
        context,
        "Standalone MDX expressions are not supported",
      );
    case "mdxJsxFlowElement":
      return transformFlowJsx(node, context);
    case "mdxJsxTextElement":
      return [
        {
          type: "paragraph",
          children: transformPhrasingNode(node, context),
        },
      ];
    case "paragraph":
      return [
        {
          type: "paragraph",
          children: transformPhrasingChildren(node.children, context),
        },
      ];
    case "heading":
      if (typeof node.depth !== "number" || node.depth < 1 || node.depth > 6) {
        unsupported(node, context, "Heading depth must be between 1 and 6");
      }
      return [
        {
          type: "heading",
          depth: node.depth,
          children: transformPhrasingChildren(node.children, context),
        },
      ];
    case "blockquote":
      return [
        {
          type: "blockquote",
          children: transformBlockChildren(node.children, context),
        },
      ];
    case "list":
      return [
        {
          ...cloneScalarFields(node, ["ordered", "start", "spread"]),
          children: (node.children ?? []).flatMap((child) => {
            if (child.type !== "listItem") {
              unsupported(child, context, "A list can contain only list items");
            }
            return transformBlockNode(child, context);
          }),
        } as AstNode,
      ];
    case "listItem":
      return [
        {
          ...cloneScalarFields(node, ["checked", "spread"]),
          children: transformBlockChildren(node.children, context),
        } as AstNode,
      ];
    case "code":
      return transformCode(node, context);
    case "thematicBreak":
      return [{ type: "thematicBreak" }];
    case "definition":
      return [
        cloneScalarFields(node, [
          "identifier",
          "label",
          "title",
          "url",
        ]) as AstNode,
      ];
    case "footnoteDefinition":
      return [
        {
          ...cloneScalarFields(node, ["identifier", "label"]),
          children: transformBlockChildren(node.children, context),
        } as AstNode,
      ];
    case "table":
      return [
        {
          ...cloneScalarFields(node, ["align"]),
          children: (node.children ?? []).flatMap((child) =>
            transformBlockNode(child, context),
          ),
        } as AstNode,
      ];
    case "tableRow":
      return [
        {
          type: "tableRow",
          children: (node.children ?? []).flatMap((child) =>
            transformBlockNode(child, context),
          ),
        },
      ];
    case "tableCell":
      return [
        {
          type: "tableCell",
          children: transformPhrasingChildren(node.children, context),
        },
      ];
    case "html":
      return unsupported(
        node,
        context,
        "Raw HTML is not supported in projected Markdown",
      );
    default:
      if (STANDARD_PHRASE_NODES.has(node.type)) {
        return [
          {
            type: "paragraph",
            children: transformPhrasingNode(node, context),
          },
        ];
      }
      return unsupported(node, context, "Unsupported Markdown block node");
  }
}

function normalizeDescription(value: string): string {
  return value.replace(/\s+/g, " ").trim();
}

export function projectMdxToMarkdown(
  source: string,
  sourcePath = "<source>",
): string {
  const parsed = matter(source);
  const title =
    typeof parsed.data.title === "string" ? parsed.data.title.trim() : "";
  const description =
    typeof parsed.data.description === "string"
      ? normalizeDescription(parsed.data.description)
      : "";
  if (!title || !description) {
    const missing = [
      !title ? "title" : null,
      !description ? "description" : null,
    ]
      .filter(Boolean)
      .join(" and ");
    throw new Error(
      `${sourcePath}: raw Markdown projection requires non-empty ${missing} frontmatter`,
    );
  }

  const bodyStart = source.indexOf(parsed.content);
  const lineOffset =
    bodyStart < 0 ? 0 : source.slice(0, bodyStart).split(/\r?\n/).length - 1;
  const context: TransformContext = { lineOffset, sourcePath };
  let parsedTree: AstNode;
  try {
    parsedTree = unified()
      .use(remarkParse)
      .use(remarkGfm)
      .use(remarkMdx)
      .parse(parsed.content) as AstNode;
  } catch (error) {
    throw new Error(
      `${sourcePath}: cannot parse MDX for raw Markdown: ${
        error instanceof Error ? error.message : String(error)
      }`,
    );
  }

  const body = transformBlockChildren(parsedTree.children, context);
  const tree: AstNode = {
    type: "root",
    children: [
      {
        type: "heading",
        depth: 1,
        children: [{ type: "text", value: title }],
      },
      {
        type: "paragraph",
        children: [{ type: "text", value: description }],
      },
      ...body,
    ],
  };
  const markdown = unified()
    .use(remarkGfm)
    .use(remarkStringify, {
      bullet: "-",
      fences: true,
      listItemIndent: "one",
      rule: "-",
    })
    .stringify(tree as never)
    .trim();
  return `${GENERATED_RAW_MARKDOWN_SENTINEL}\n\n${markdown}\n`;
}

export async function collectRawMarkdownPages(
  rootDir = process.cwd(),
): Promise<{
  pages: RawMarkdownPage[];
}> {
  const resolvedRoot = path.resolve(rootDir);
  const docsRoot = path.join(resolvedRoot, "src/pages/docs");
  const sourceRelativePaths = (
    await fg("**/*.mdx", {
      cwd: docsRoot,
      onlyFiles: true,
    })
  )
    .map((item) => item.replace(/\\/g, "/"))
    .sort();
  if (sourceRelativePaths.length === 0) {
    throw new Error(`${docsRoot} does not contain any .mdx pages`);
  }

  validateDocumentationSourcePaths(sourceRelativePaths);
  const routes = sourceRelativePaths.map(rawMarkdownRouteForSource);
  validateRawRouteCollisions(routes);
  validateExportedFileBijection(routes);
  const pages = await Promise.all(
    routes.map(async (route): Promise<RawMarkdownPage> => {
      const sourcePath = path.join(docsRoot, route.sourceRelativePath);
      const source = await fs.promises.readFile(sourcePath, "utf8");
      return {
        ...route,
        markdown: projectMdxToMarkdown(
          source,
          path.relative(resolvedRoot, sourcePath).replace(/\\/g, "/"),
        ),
        sourcePath,
      };
    }),
  );
  return { pages };
}

function isMissingFile(error: unknown): boolean {
  return (
    typeof error === "object" &&
    error !== null &&
    "code" in error &&
    error.code === "ENOENT"
  );
}

async function readIfPresent(file: string): Promise<string | null> {
  try {
    return await fs.promises.readFile(file, "utf8");
  } catch (error) {
    if (isMissingFile(error)) return null;
    throw error;
  }
}

function generatedFile(contents: string): boolean {
  return contents.startsWith(`${GENERATED_RAW_MARKDOWN_SENTINEL}\n`);
}

function reservedRawMarkdownPath(relative: string): boolean {
  const normalized = relative.replace(/\\/g, "/");
  return normalized === "docs.md" || normalized.startsWith("docs/");
}

function outputPath(publicRoot: string, relative: string): string {
  const resolvedPublicRoot = path.resolve(publicRoot);
  const resolved = path.resolve(resolvedPublicRoot, relative);
  if (!resolved.startsWith(`${resolvedPublicRoot}${path.sep}`)) {
    throw new Error(`Raw Markdown output escapes public/: ${relative}`);
  }
  return resolved;
}

async function removeEmptyParents(
  directory: string,
  publicRoot: string,
): Promise<void> {
  let current = path.resolve(directory);
  const stop = path.resolve(publicRoot);
  while (current !== stop && current.startsWith(`${stop}${path.sep}`)) {
    try {
      await fs.promises.rmdir(current);
    } catch (error) {
      if (
        isMissingFile(error) ||
        (typeof error === "object" &&
          error !== null &&
          "code" in error &&
          ["ENOTEMPTY", "EEXIST"].includes(String(error.code)))
      ) {
        return;
      }
      throw error;
    }
    current = path.dirname(current);
  }
}

export async function generateRawMarkdown({
  check = false,
  rootDir = process.cwd(),
}: RawMarkdownGenerationOptions = {}): Promise<RawMarkdownGenerationResult> {
  const resolvedRoot = path.resolve(rootDir);
  const publicRoot = path.join(resolvedRoot, "public");
  const { pages } = await collectRawMarkdownPages(resolvedRoot);
  const expected = new Map<string, RawMarkdownPage>();
  const existing = new Map<string, string | null>();

  for (const page of pages) {
    const target = outputPath(publicRoot, page.outputRelativePath);
    expected.set(target, page);
    const contents = await readIfPresent(target);
    if (contents !== null && !generatedFile(contents)) {
      throw new Error(
        `Refusing to overwrite non-generated raw Markdown file: ${path.relative(
          resolvedRoot,
          target,
        )}`,
      );
    }
    existing.set(target, contents);
  }

  const publicMarkdownFiles = await fg("**/*.md", {
    cwd: publicRoot,
    onlyFiles: true,
    followSymbolicLinks: false,
  });
  const outdated = [...expected].filter(
    ([target, page]) =>
      existing.get(target) !== null && existing.get(target) !== page.markdown,
  );
  const stale: string[] = [];
  for (const relative of publicMarkdownFiles.sort()) {
    const target = outputPath(publicRoot, relative);
    if (expected.has(target)) continue;
    const contents = await fs.promises.readFile(target, "utf8");
    if (generatedFile(contents)) {
      stale.push(target);
    } else if (reservedRawMarkdownPath(relative)) {
      throw new Error(
        `Refusing unmanaged file in the reserved raw Markdown namespace: ${path.relative(
          resolvedRoot,
          target,
        )}`,
      );
    }
  }

  if (check) {
    return {
      outdatedCount: outdated.length,
      projectedCount: pages.length,
      removedCount: 0,
      staleCount: stale.length,
      writtenCount: 0,
    };
  }

  let writtenCount = 0;
  for (const [target, page] of expected) {
    if (existing.get(target) === page.markdown) continue;
    await fs.promises.mkdir(path.dirname(target), { recursive: true });
    await fs.promises.writeFile(target, page.markdown);
    writtenCount += 1;
  }

  for (const target of stale) {
    const contents = await fs.promises.readFile(target, "utf8");
    if (!generatedFile(contents)) {
      throw new Error(
        `Refusing to delete raw Markdown file after its generated sentinel changed: ${path.relative(
          resolvedRoot,
          target,
        )}`,
      );
    }
    await fs.promises.unlink(target);
    await removeEmptyParents(path.dirname(target), publicRoot);
  }

  return {
    outdatedCount: outdated.length,
    projectedCount: pages.length,
    removedCount: stale.length,
    staleCount: stale.length,
    writtenCount,
  };
}

export async function runRawMarkdownCli(
  args = process.argv.slice(2),
  rootDir = process.cwd(),
): Promise<RawMarkdownGenerationResult> {
  const unexpected = args.filter((arg) => arg !== "--check");
  if (unexpected.length > 0) {
    throw new Error(
      `Unknown raw Markdown generator argument(s): ${unexpected.join(", ")}`,
    );
  }
  const check = args.includes("--check");
  const result = await generateRawMarkdown({ check, rootDir });
  if (check) {
    const issues = [
      result.outdatedCount > 0
        ? `${result.outdatedCount} outdated generated raw Markdown file(s) differ from their MDX source`
        : null,
      result.staleCount > 0
        ? `${result.staleCount} stale generated raw Markdown file(s) remain`
        : null,
    ].filter((issue): issue is string => issue !== null);
    if (issues.length > 0) {
      throw new Error(`${issues.join("; ")}. Run \`bun run build:raw\`.`);
    }
    console.log(
      `Projected ${result.projectedCount} raw Markdown routes; generated files are not required in --check mode.`,
    );
  } else {
    console.log(
      `Generated ${result.projectedCount} raw Markdown routes; wrote ${result.writtenCount} and removed ${result.removedCount} stale file(s).`,
    );
  }
  return result;
}

if (import.meta.main) {
  try {
    await runRawMarkdownCli();
  } catch (error) {
    console.error(error instanceof Error ? error.message : String(error));
    process.exit(1);
  }
}
