#!/bin/bash
echo "Running pre-commit hooks..." && \
echo "Running build:prep..."
bun run build:prep
echo "Staging changes from build:prep..."
# add all page changes after build:prep
git add src/pages/articles/*.mdx src/pages/docs/*.mdx
echo "Running lint-staged..."
lint-staged
echo "Pre-commit hooks completed successfully. ✨"
exit 0
